name: macos

on:
  push:
  workflow_dispatch:
    inputs:
      codespace:
        description: 'Name of the codespace to connect to'
        required: true

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - run: bash macos.sh

    - name: Debug in Codespace
      if: failure()
      uses: dlemstra/github-actions-debugger@main
      with:
        token: ${{ secrets.TOKEN_FOR_CODESPACES }}
        codespace: ${{ inputs.codespace }}