name: windows

on:
  workflow_dispatch:
    inputs:
      codespace:
        description: 'Name of the codespace to connect to'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - run: |
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
        Start-Service sshd
      name:  Start SSH Server

    - run: windows.cmd

    - name: Debug in Codespace
      if: failure()
      uses: dlemstra/github-actions-debugger@main
      with:
        token: ${{ secrets.TOKEN_FOR_CODESPACES }}
        codespace: ${{ inputs.codespace }}
